### ISSUE TITLE
请不要再提交vscode那边的issue了

### ISSUE THREAD

**Issue by barryblueice** [ABC-IDE/OpenABC-IDE#199]
我们在那边的issue已经给开发者造成了诸多麻烦，请大家不要再去那边提交issue了。
我也很理解大家的心情，当初看到这玩意儿的时候我也是很震惊很不爽的，毕竟这玩意就加个vip套皮然后就宣称国产自研，你说这些不如信我是秦始皇。
确实国产cec-ide很垃圾就是个套壳，丢国人的脸。但我们在那边乱提交issue不也是很丢脸的事情吗？
这里是GitHub，不是QQ群。

**Comment by chenliang7558** [comment]
没毛病

**Comment by barryblueice** [comment]
已经艾特管理员请求锁定issue了（虽然不知道他们能不能看到）

**Comment by 1713612859** [comment]
你真的是丢死人，国外都在转发。

**Comment by bmphjhu906** [comment]
你说的对这里是GitHub，不是QQ群，大家畅所欲言

**Comment by ESUAdmin** [comment]
能体现翻墙中国人劣根性的事情应该多做，让外国人知道国人开发者都是没见过世面的小丑

**Comment by NorthSecond** [comment]
> 你真的是丢死人，国外都在转发。

有没有可能几个小时时间给全体社区成员搞几百封邮件也是一个烦人且无聊的行为呢。

**Comment by Lhcfl** [comment]
Github上确实有一堆开玩笑式的issues，倒是不必苛责楼主。倒不如说这件事体现出的狂欢情绪，某些东西完全不尊重开源社区成员的感受，才是某些东西最丢人的地方。

**Comment by qian-o** [comment]
丢 死人啦

**Comment by Lhcfl** [comment]
你自己知道的话，为什么不去你那个issues页面编辑一下，换成你这条呢

**Comment by barryblueice** [comment]
> 你自己知道的话，为什么不去你那个issues页面编辑一下，换成你这条呢

已经在编辑了

**Comment by so1ve** [comment]
CEC丢人，把github当论坛版聊的一群傻逼更丢人

**Comment by Geek-Quantum** [comment]
怎么了事情闹大了 知道了 这里不是QQ 微信 微博 大家可以敞开的聊

**Comment by Lhcfl** [comment]
> 这里不是QQ 微信 微博 大家可以敞开的聊

你以为没有censorship等于你可以无法无天？你知道这是spam吗？这是违反Github Community Guidelines的，你们这群人能不能尊重一下正常开发者的使用体验？

> Keep it tidy. Make the effort to put things in the right place, so that we can spend more time discussing and less time cleaning up. So:
> 
> Don’t start a discussion in the wrong category.
> Don’t cross-post the same thing in multiple discussions.
> Don’t post no-content replies.
> Don't "bump" posts, unless you have new and relevant information to share.
> Don’t divert a discussion by changing it midstream.
>

**Comment by so1ve** [comment]
@Lhcfl 这种人一看就是看热闹不嫌事大的，点开主页一看什么都没有

**Comment by yejimeiming** [comment]
> @Lhcfl 这种人一看就是看热闹不嫌事大的，点开主页一看什么都没有

周五了，比较闲 😂

**Comment by FriedTomatoes** [comment]
就骗补贴用的呗

**Comment by xTaiwanPingLord** [comment]
> 怎么了事情闹大了 知道了 这里不是QQ 微信 微博 大家可以敞开的聊

享有言論自由的同時也要負起對應的責任。
不是擁有自由就可以為所欲為，仍要符合該平台的規範。

發送幾個通知是好意，發送大量的通知就變spam了
